# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:  
  build:   
# the below runner is an available github hosted runners
# we can have and our local hosted runners if we want to run specific build
# under our machines
    runs-on: ubuntu-latest   
    steps:    
      - uses: actions/checkout@v3  
      
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
